export const FETCH_RECIPES = 'FETCH_RECIPES'
export const ADD_RECIPES = 'ADD_RECIPES'

export const FILTER_BY_LABEL = 'FILTER_BY_LABEL'
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE'
export const FILTER_BY_FREETEXT = 'FILTER_BY_FREETEXT'
export const RESET_FILTER = 'RESET_FILTER'
